### ISSUE TITLE
no method matching rowvals

### ISSUE THREAD

**Issue by wang22ti** [wuliwei9278/SQL-Rank#1]
hello, I am using julia-1.0.3 to run this code, but meet an error like this:
`
ERROR: MethodError: no method matching rowvals(::LinearAlgebra.Adjoint{Int64,SparseMatrixCSC{Int64,Int64}})
`
what should I do?

**Comment by wuliwei9278** [comment]
The codes only work on 0.6. Back then, there is no Julia 1.0. Let me update the README file. Thanks for pointing out. Also evaluation part does not do sampling so it would be slow to calculate precision for a large dataset. For movielens1m, it is okay without sampling.
